site_name: xRally Docs
site_description: Official xRally Documentation
site_author: xRally team
site_url: https://xrally.org
repo_name: xrally/xrally
repo_url: https://github.com/xrally/xrally
edit_uri: ""

theme:
    name: material
    feature:
        tabs: true

pages:
  - Overview:
    - Why xRally?: index.md
    - Quick Start: overview/quick_start.md
    - Components: overview/components.md
    - Export Results: overview/export.md
    - Install Options: overview/install.md
    - DB & Upgrades: overview/upgrades.md
    - Community: overview/community.md
    - License: overview/license.md

  - Conitnious Integration:
    - Overview: ci/index.md
    - xRally & Jenkins: ci/jenkins.md
    - xRally & Travis: ci/travis.md
    - xRally & CircleCI: ci/circleci.md

  - Conitnious Monitoring:
    - Overview: cm/index.md
    - xRally, Elastic & Grafana: cm/elastic_grafana.md

  - Architecture:
    - High Level: arch/index.md
    - Glossary: arch/glossary.md
    - Plugins Mechanism: arch/plugins.md
    - Mastering Env: arch/env.md
    - Mastering Task: arch/task.md
    - Mastering Verify: arch/verify.md

  - API Reference:
    - CLI Reference: ref/cli.md

  - Plugins:
    - Overview: plugins/index.md
